### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by alvarotrigo** [Alofoxx/oauth2-gumroad#1]
It seems like the example in the docs is not working.

The `$apiDomain` variable should probably be `https://gumroad.com` instead of `https://api.gumroad.com`.
At least, that's how the authorize URL looks like:

> https://gumroad.com/oauth/authorize?response_type=code&client_id=xxxxxx&redirect_uri=xxxxxxsettings&scope=view_sales%20edit_products

**Comment by Alofoxx** [comment]
I will double check

**Comment by Alofoxx** [comment]
https://api.gumroad.com/oauth seems to serve the same oauth2 endpoint as https://gumroad.com/oauth 

I will update it to remove the subdomain but it works with either the same.

**Comment by Alofoxx** [comment]
Was there an error you encountered though? Because it is working as-is for me...

**Comment by alvarotrigo** [comment]
Interesting... I'll check again!
