### ISSUE TITLE
getExpires method returns null

### ISSUE THREAD

**Issue by alvarotrigo** [Alofoxx/oauth2-gumroad#2]
`getExpires` method returns `null`.
Also, any docs regarding how often do tokens expire? Can't find anything on the Gumroad API.

**Comment by Alofoxx** [comment]
I had the same question and contacted the Gumroad support team. They informed me that they never expire. :/ 
If they fix that in the future it should work.

![image](https://user-images.githubusercontent.com/1343190/97480740-13aa5300-1911-11eb-8db6-89a95cc36176.png)

**Comment by Alofoxx** [comment]
Closing since this is what Gumroad returns.

**Comment by alvarotrigo** [comment]
Thanks for the info! 👍
